export const CHANGE_ITEM_POSITION = "CHANGE_ITEM_POSITION";
export const CHANGE_ITEM_LIST = "CHANGE_ITEM_LIST";
export const CHANGE_ITEM_SHOW = "CHANGE_ITEM_SHOW";
export const SET_LISTS = "SET_LISTS";